# Generated by Django 5.2.8 on 2026-03-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Producto')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('unit', models.CharField(default='unidad', max_length=30, verbose_name='Unidad')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_stock', models.IntegerField(default=0, verbose_name='Stock esperado')),
                ('counted_stock', models.IntegerField(default=0, verbose_name='Stock contado')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='audits.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Registro de Inventario',
                'verbose_name_plural': 'Registros de Inventario',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
