# Generated by Django 5.2.8 on 2026-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='damaged_stock',
            field=models.IntegerField(default=0, verbose_name='Unidades dañadas'),
        ),
    ]
